title: minhee
author: minhee
email: mini940511@gmail.com

url: "https://minheeyoon.github.io/"
social_username: himin_h
behance_username: mhyoon
drb_username: miniY

# Collections
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

github: minheeyoon
