title: minhee
author: minhee
email: mini940511@gmail.com
description: minhee test
url: "https://minheeyoon.github.io/"
social_username: himin_h
behance_username: mhyoon
drb_username: miniY

# Collections
collections:
  projects:
    output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from

github: [metadata]

theme_color: white
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
